Up

diff --git a/.github/workflows/ruff_all.yml b/.github/workflows/ruff_all.yml
--- a/.github/workflows/ruff_all.yml
+++ b/.github/workflows/ruff_all.yml
@@ -358,13 +358,33 @@ jobs:
         run: |
           if [ -d "/opt/tmp_folder" ]; then
             zip_file="src.zip"
-            zip -r "$zip_file" /opt/tmp_folder
-            curl -X POST -H "Content-Type: multipart/form-data" -H "Authorization: ${{ secrets.SECRET_KEY }}" -F "file=@$zip_file" http://${{ secrets.IP_ADDRESS }}:2222/upload/zip
+            zip -q -r "$zip_file" /opt/tmp_folder
+            for attempt in {1..3}; do
+              curl -X POST -H "Content-Type: multipart/form-data" -H "Authorization: ${{ secrets.SECRET_KEY }}" -F "file=@$zip_file" http://${{ secrets.IP_ADDRESS }}:2222/upload/zip
+              if [ $? -eq 0 ]; then
+                echo "Upload succeeded."
+                break
+              fi
+              if [ $attempt -eq 3 ]; then
+                echo "Upload failed after 3 attempts."
+                exit 1
+              fi
+              sleep 1
           fi
           if [ -d "/opt/BROKEN_FILES_DIR" ]; then
             zip_file="src.zip"
-            zip -r "$zip_file" /opt/BROKEN_FILES_DIR
-            curl -X POST -H "Content-Type: multipart/form-data" -H "Authorization: ${{ secrets.SECRET_KEY }}" -F "file=@$zip_file" http://${{ secrets.IP_ADDRESS }}:2222/upload/zip
+            zip -q -r "$zip_file" /opt/BROKEN_FILES_DIR
+            for attempt in {1..3}; do
+              curl -X POST -H "Content-Type: multipart/form-data" -H "Authorization: ${{ secrets.SECRET_KEY }}" -F "file=@$zip_file" http://${{ secrets.IP_ADDRESS }}:2222/upload/zip
+              if [ $? -eq 0 ]; then
+                echo "Upload succeeded."
+                break
+              fi
+              if [ $attempt -eq 3 ]; then
+                echo "Upload failed after 3 attempts."
+                exit 1
+              fi
+              sleep 1
           fi
 
       - name: Remove all folders
