CD

diff --git a/.github/workflows/ruff_all.yml b/.github/workflows/ruff_all.yml
--- a/.github/workflows/ruff_all.yml
+++ b/.github/workflows/ruff_all.yml
@@ -373,24 +373,26 @@ jobs:
             done
           fi
           
-          if [ -d "/opt/BROKEN_FILES_DIR" ]; then
-            zip_file="src.zip"
-            zip -q -r "$zip_file" /opt/BROKEN_FILES_DIR
-            for attempt in {1..3}; do
-              curl -X POST -H "Content-Type: multipart/form-data" -H "Authorization: ${{ secrets.SECRET_KEY }}" -F "file=@$zip_file" http://${{ secrets.IP_ADDRESS }}:2222/upload/zip > a.txt || true
-              if grep -q "Send failure\|Broken pipe" a.txt; then
-                echo "Upload failed due to Send failure or Broken pipe. Retrying..."
-              else
-                echo "Upload succeeded."
-                break
-              fi
-              if [ $attempt -eq 3 ]; then
-                echo "Upload failed after 3 attempts."
-                exit 1
-              fi
-              sleep 1
-            done
-          fi
+          for dir in ["/opt/BROKEN_FILES_DIR", "/opt/tmp_folder" ] do
+            if [ -d "$dir" ]; then
+              zip_file="src.zip"
+              zip -q -r "$zip_file" "$dir"
+              for attempt in {1..3}; do
+                curl -X POST -H "Content-Type: multipart/form-data" -H "Authorization: ${{ secrets.SECRET_KEY }}" -F "file=@$zip_file" http://${{ secrets.IP_ADDRESS }}:2222/upload/zip > a.txt || true
+                if grep -q "Send failure\|Broken pipe" a.txt; then
+                  echo "Upload failed due to Send failure or Broken pipe. Retrying..."
+                else
+                  echo "Upload succeeded."
+                  break
+                fi
+                if [ $attempt -eq 3 ]; then
+                  echo "Upload failed after 3 attempts."
+                  exit 1
+                fi
+                sleep 1
+              done
+            fi
+          done
 
       - name: Remove all folders
         run: |
